### ISSUE TITLE
feat: add domain/model with in-memory repository

### ISSUE THREAD

**Issue by tingtt** [fickle-project/fickle#3]
## Tasks

- [x] `users`
- [x] `issues`
- [x] `schedules`

### `domain/users`
- [x] Add test to `users` domain.
  - [x] Refactor errors.
### `domain/issues`
- [x] Add more test cases to Update/Remove func.
- [x] Add tests validating no update.
- [x] Refactor query parameters.
### `domain/schedules`
- [x] Add tests of Find* func.
